# -*- coding: utf-8 -*-
"""Canonical Moscow okrug for each metro slug in the master list.

Assignment follows the station location, not the station name.
Ambiguous stations still have one canonical okrug; the reason is in NOTES.
"""

OKRUGS = {
    "cao": "ЦАО",
    "sao": "САО",
    "svao": "СВАО",
    "vao": "ВАО",
    "yuvao": "ЮВАО",
    "yuao": "ЮАО",
    "yuzao": "ЮЗАО",
    "zao": "ЗАО",
    "szao": "СЗАО",
    "zelao": "ЗелАО",
    "nao": "НАО",
    "tao": "ТАО",
}

# Administrative neighbors for internal linking. Not a URL hierarchy.
# kind=border is a shared boundary; kind=practical is a transport link
# for an exclave that has no shared boundary.
OKRUG_NEIGHBORS = [
    ("cao", "zao", 1, "border"),
    ("cao", "yuao", 2, "border"),
    ("cao", "sao", 3, "border"),
    ("cao", "yuvao", 4, "border"),
    ("sao", "svao", 1, "border"),
    ("sao", "szao", 2, "border"),
    ("sao", "cao", 3, "border"),
    ("svao", "sao", 1, "border"),
    ("svao", "vao", 2, "border"),
    ("svao", "cao", 3, "border"),
    ("vao", "svao", 1, "border"),
    ("vao", "yuvao", 2, "border"),
    ("vao", "cao", 3, "border"),
    ("yuvao", "vao", 1, "border"),
    ("yuvao", "yuao", 2, "border"),
    ("yuvao", "cao", 3, "border"),
    ("yuao", "yuvao", 1, "border"),
    ("yuao", "yuzao", 2, "border"),
    ("yuao", "cao", 3, "border"),
    ("yuao", "nao", 4, "border"),
    ("yuzao", "yuao", 1, "border"),
    ("yuzao", "zao", 2, "border"),
    ("yuzao", "cao", 3, "border"),
    ("yuzao", "nao", 4, "border"),
    ("zao", "szao", 1, "border"),
    ("zao", "yuzao", 2, "border"),
    ("zao", "cao", 3, "border"),
    ("zao", "nao", 4, "border"),
    ("szao", "sao", 1, "border"),
    ("szao", "zao", 2, "border"),
    ("szao", "cao", 3, "border"),
    ("zelao", "szao", 1, "practical"),
    ("nao", "yuao", 1, "border"),
    ("nao", "yuzao", 2, "border"),
    ("nao", "zao", 3, "border"),
    ("nao", "tao", 4, "border"),
    ("tao", "nao", 1, "border"),
]

GROUPS = {
    "cao": [
        "aleksandrovskij-sad",
        "arbatskaya",
        "barrikadnaya",
        "baumanskaya",
        "belorusskaya",
        "biblioteka-imeni-lenina",
        "borovickaya",
        "chehovskaya",
        "chistye-prudy",
        "chkalovskaya",
        "cvetnoj-bulvar",
        "delovoj-centr",
        "dobryninskaya",
        "dostoevskaya",
        "frunzenskaya",
        "kitaj-gorod",
        "komsomolskaya",
        "krasnopresnenskaya",
        "krasnoselskaya",
        "krasnye-vorota",
        "krestyanskaya-zastava",
        "kropotkinskaya",
        "krymskaya",
        "kurskaya",
        "kuzneckij-most",
        "lubyanka",
        "luzhniki",
        "marksistskaya",
        "mayakovskaya",
        "mendeleevskaya",
        "mezhdunarodnaya",
        "novokuzneckaya",
        "novoslobodskaya",
        "ohotnyj-ryad",
        "oktyabrskaya",
        "park-kultury",
        "paveleckaya",
        "ploshchad-ilicha",
        "ploshchad-revolyucii",
        "polyanka",
        "proletarskaya",
        "prospekt-mira",
        "pushkinskaya",
        "rimskaya",
        "serpuhovskaya",
        "shelepiha",
        "smolenskaya",
        "sportivnaya",
        "sretenskij-bulvar",
        "suharevskaya",
        "taganskaya",
        "teatralnaya",
        "tretyakovskaya",
        "trubnaya",
        "turgenevskaya",
        "tverskaya",
        "ulica-1905-goda",
        "vystavochnaya",
    ],
    "sao": [
        "aeroport",
        "baltijskaya",
        "begovaya",
        "butyrskaya",
        "cska",
        "dinamo",
        "dmitrovskaya",
        "fonvizinskaya",
        "horoshevskaya",
        "hovrino",
        "koptevo",
        "lihobory",
        "okruzhnaya",
        "panfilovskaya",
        "petrovskij-park",
        "petrovsko-razumovskaya",
        "polezhaevskaya",
        "rechnoj-vokzal",
        "savelovskaya",
        "seligerskaya",
        "sokol",
        "timiryazevskaya",
        "ulica-milashenkova",
        "verhnie-lihobory",
        "vodnyj-stadion",
        "vojkovskaya",
        "zorge",
    ],
    "svao": [
        "alekseevskaya",
        "altufevo",
        "babushkinskaya",
        "bibirevo",
        "botanicheskij-sad",
        "marina-roshcha",
        "medvedkovo",
        "otradnoe",
        "rizhskaya",
        "rostokino",
        "sviblovo",
        "telecentr",
        "ulica-akademika-koroleva",
        "ulica-sergeya-ejzenshtejna",
        "vdnh",
        "vladykino",
        "vystavochnyj-centr",
    ],
    "vao": [
        "belokamennaya",
        "bulvar-rokossovskogo",
        "cherkizovskaya",
        "elektrozavodskaya",
        "izmajlovskaya",
        "lokomotiv",
        "novogireevo",
        "novokosino",
        "partizanskaya",
        "perovo",
        "pervomajskaya",
        "preobrazhenskaya-ploshchad",
        "semenovskaya",
        "shchelkovskaya",
        "shosse-entuziastov",
        "sokolinaya-gora",
    ],
    "yuvao": [
        "andronovka",
        "aviamotornaya",
        "borisovo",
        "bratislavskaya",
        "kotelniki",
        "kozhuhovskaya",
        "kuzminki",
        "lermontovskij-prospekt",
        "lyublino",
        "marino",
        "nizhegorodskaya",
        "novohohlovskaya",
        "pechatniki",
        "ryazanskij-prospekt",
        "tekstilshchiki",
        "ugreshskaya",
        "volgogradskij-prospekt",
        "volzhskaya",
        "vyhino",
        "zhulebino",
    ],
    "yuao": [
        "alma-atinskaya",
        "annino",
        "avtozavodskaya",
        "caricyno",
        "chertanovskaya",
        "domodedovskaya",
        "kantemirovskaya",
        "kashirskaya",
        "kolomenskaya",
        "krasnogvardejskaya",
        "leninskij-prospekt",
        "nagatinskaya",
        "nagornaya",
        "orehovo",
        "prazhskaya",
        "shabolovskaya",
        "shipilovskaya",
        "tehnopark",
        "tulskaya",
        "ulica-akademika-yangelya",
        "varshavskaya",
        "verhnie-kotly",
        "yuzhnaya",
        "zil",
        "zyablikovo",
    ],
    "yuzao": [
        "belyaevo",
        "bitcevskij-park",
        "bulvar-admirala-ushakova",
        "buninskaya-alleya",
        "kahovskaya",
        "kaluzhskaya",
        "konkovo",
        "lesoparkovaya",
        "nahimovskij-prospekt",
        "novoyasenevskaya",
        "novye-cheremushki",
        "ploshchad-gagarina",
        "profsoyuznaya",
        "prospekt-vernadskogo",
        "sevastopolskaya",
        "teplyj-stan",
        "ulica-gorchakova",
        "ulica-skobelevskaya",
        "ulica-starokachalovskaya",
        "yasenevo",
    ],
    "zao": [
        "bagrationovskaya",
        "filevskij-park",
        "fili",
        "kievskaya",
        "krylatskoe",
        "kuncevskaya",
        "kutuzovskaya",
        "lomonosovskij-prospekt",
        "minskaya",
        "molodezhnaya",
        "park-pobedy",
        "pionerskaya",
        "ramenki",
        "slavyanskij-bulvar",
        "studencheskaya",
        "troparevo",
        "universitet",
        "vorobevy-gory",
        "yugo-zapadnaya",
    ],
    "szao": [
        "myakinino",
        "oktyabrskoe-pole",
        "planernaya",
        "pyatnickoe-shosse",
        "shchukinskaya",
        "shodnenskaya",
        "spartak",
        "streshnevo",
        "strogino",
        "tushinskaya",
        "volokolamskaya",
    ],
    "nao": [
        "rumyancevo",
        "salarevo",
    ],
    "zelao": [],
    "tao": [],
}

NOTES = {
    "andronovka": "Граница Лефортово/Нижегородский (ЮВАО) и Перово (ВАО). Канонический округ для перелинковки — ЮВАО. Второй URL не создаётся.",
    "avtozavodskaya": "Даниловский район относится к ЮАО, не к ЦАО.",
    "baltijskaya": "Станция МЦК у Войковского (САО), рядом граница с Покровским-Стрешневом (СЗАО). Канонический округ — САО.",
    "dostoevskaya": "Южнее Марьиной Рощи (СВАО). Канонический округ — ЦАО (Тверской).",
    "elektrozavodskaya": "Граница Соколиной Горы (ВАО) и Басманного (ЦАО). Канонический округ — ВАО. Второй URL не создаётся.",
    "horoshevskaya": "Станция в Хорошёвском районе (САО). Не относить к СЗАО только из-за похожего названия Хорошёво-Мнёвники.",
    "kievskaya": "Вестибюли у Киевского вокзала, район Дорогомилово (ЗАО). Площадь воспринимается как центр, но административно это не ЦАО.",
    "kotelniki": "Станция на границе Выхино-Жулебино (ЮВАО) и города Котельники Московской области. Для окружной перелинковки выбран ЮВАО. Это не заменяет городскую страницу Котельников и не создаёт второй URL станции.",
    "leninskij-prospekt": "Граница Донского (ЮАО), Якиманки (ЦАО) и Гагаринского (ЮЗАО). Канонический округ — ЮАО. Второй URL не создаётся.",
    "myakinino": "Станция находится в Красногорске (Московская область), а не в округе Москвы. Для архитектурной перелинковки с округами выбран ближайший СЗАО (Строгино). Городская страница Красногорска, если она есть у услуги, этим не заменяется.",
    "nahimovskij-prospekt": "Граница Зюзино/Котловка (ЮЗАО) и Нагорного (ЮАО). Канонический округ — ЮЗАО. Второй URL не создаётся.",
    "ploshchad-gagarina": "Площадь Гагарина на стыке Гагаринского (ЮЗАО), Донского (ЮАО) и Якиманки (ЦАО). Канонический округ — ЮЗАО. Второй URL не создаётся.",
    "ploshchad-ilicha": "Таганский район (ЦАО) у границы с Лефортово (ЮВАО). Канонический округ — ЦАО.",
    "proletarskaya": "Таганский район относится к ЦАО, не к ЮВАО.",
    "prospekt-mira": "Станция у Садового кольца, Мещанский район (ЦАО). Проспект продолжается в СВАО, но сама станция к СВАО не относится.",
    "prospekt-vernadskogo": "Район Проспект Вернадского относится к ЮЗАО, не к ЗАО.",
    "rimskaya": "Парная к Площади Ильича: Таганский район (ЦАО) у границы с Лефортово (ЮВАО). Канонический округ — ЦАО.",
    "rizhskaya": "Граница Алексеевского (СВАО) и Мещанского (ЦАО) у Рижского вокзала. Канонический округ — СВАО. Второй URL не создаётся.",
    "sevastopolskaya": "Граница Зюзино (ЮЗАО) и Чертаново (ЮАО). Канонический округ — ЮЗАО. Второй URL не создаётся.",
    "shabolovskaya": "Донской район относится к ЮАО, не к ЦАО.",
    "shelepiha": "Пресненский район (ЦАО) у границы с Дорогомилово (ЗАО). Канонический округ — ЦАО.",
    "shosse-entuziastov": "Граница Соколиной Горы (ВАО) и Лефортово (ЮВАО). Канонический округ — ВАО. Второй URL не создаётся.",
    "streshnevo": "Граница Покровского-Стрешнева (СЗАО) и Сокола (САО). Канонический округ — СЗАО. Второй URL не создаётся.",
    "ulica-milashenkova": "Граница Бутырского (САО) и Марьиной Рощи/Останкинского (СВАО). Канонический округ — САО. Второй URL не создаётся.",
    "universitet": "Раменки относятся к ЗАО. Юго-западное направление Сокольнической линии не делает станцию страницей ЮЗАО.",
    "varshavskaya": "Канонический округ — ЮАО (Нагорный); рядом Зюзино (ЮЗАО). Второй URL не создаётся.",
    "verhnie-kotly": "Граница Нагорного (ЮАО) и Котловки (ЮЗАО). Канонический округ — ЮАО. Второй URL не создаётся.",
    "vladykino": "Граница Отрадного (СВАО) и Бескудниковского/Западного Дегунино (САО). Канонический округ — СВАО. Второй URL не создаётся.",
    "vorobevy-gory": "Станция на Лужнецком метромосту, на стыке Раменок (ЗАО), Гагаринского (ЮЗАО) и Хамовников (ЦАО). Канонический округ — ЗАО. Второй URL не создаётся.",
    "yugo-zapadnaya": "Тропарёво-Никулино относится к ЗАО. Название станции не используется как признак ЮЗАО.",
    "zil": "Даниловский район (ЮАО); площадка ЗИЛ граничит с Южнопортовым (ЮВАО). Канонический округ — ЮАО.",
    "zorge": "Граница Хорошёвского (САО) и Хорошёво-Мнёвников (СЗАО). Канонический округ — САО. Второй URL не создаётся.",
}


def assignment():
    mapping = {}
    for slug, stations in GROUPS.items():
        for station in stations:
            if station in mapping:
                raise SystemExit(f"duplicate assignment: {station}")
            mapping[station] = slug
    return mapping
